CREATE TABLE `millionaires` (
  `id` int(255) NULL DEFAULT NULL AUTO_INCREMENT,
  `question` varchar(255) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `answer_A` varchar(255) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `answer_B` varchar(255) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `answer_C` varchar(255) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `answer_D` varchar(255) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `correct_answer` varchar(255) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8_polish_ci;

INSERT INTO `millionaires` (`id`, `question`, `answer_A`, `answer_B`, `answer_C`, `answer_D`, `correct_answer`) VALUES
(1, 'Pytanie testowa nr1', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(2, 'Pytanie testowa nr2', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(3, 'Pytanie testowa nr3', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(4, 'Pytanie testowa nr4', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(5, 'Pytanie testowa nr5', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(6, 'Pytanie testowa nr6', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(7, 'Pytanie testowa nr7', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(8, 'Pytanie testowa nr8', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(9, 'Pytanie testowa nr9', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(10, 'Pytanie testowa nr10', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(11, 'Pytanie testowa nr11', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(12, 'Pytanie testowa nr12', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(13, 'Pytanie testowa nr13', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(14, 'Pytanie testowa nr14', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(15, 'Pytanie testowa nr15', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(16, 'Pytanie testowa nr16', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(17, 'Pytanie testowa nr17', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(18, 'Pytanie testowa nr18', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(19, 'Pytanie testowa nr19', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(20, 'Pytanie testowa nr20', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(21, 'Pytanie testowa nr21', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(22, 'Pytanie testowa nr22', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(23, 'Pytanie testowa nr23', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(24, 'Pytanie testowa nr24', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(25, 'Pytanie testowa nr25', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(26, 'Pytanie testowa nr26', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(27, 'Pytanie testowa nr27', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(28, 'Pytanie testowa nr28', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(29, 'Pytanie testowa nr29', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(31, 'Pytanie testowa nr31', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(32, 'Pytanie testowa nr32', 'odp A', 'odp B', 'odp C', 'odp D', 'A'),
(33, 'Pytanie testowa nr33', 'odp A', 'odp B', 'odp C', 'odp D', 'A');
